on: [issue_comment, push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - uses: lhotari/action-upterm@v1
      - run: |
          echo start
          pwd
          ls -la
          # hub pr checkout ${{ github.event.issue.number }}
          echo done
