# fastlane build platform:android

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH
        uses: mxschmitt/action-tmate@v3

  test:
    # if: |
    #   github.event.issue.pull_request &&
    #   startsWith(github.event.comment.body, '/fastlane')

    runs-on: ubuntu-latest

    steps:
      - name: print github-script internals
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(JSON.stringify(context, null, 2))
            console.log(JSON.stringify(github, null, 2))

      - id: get-pr-branch
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.issue.html_url }}
        run: |
          echo "BRANCH=$(gh pr view --json headRefName --jq .headRefName $PR_URL)"

      - uses: circleci-public/trigger-circleci-pipeline-action@v1.2.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN_SZ }}
        with:
          target-branch: ${{ steps.get-pr-branch.outputs.BRANCH }}
          GHA_Meta: ${{ github.event.comment.body }}
