on: issue_comment
jobs:
  myjob:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          echo start
          pwd
          ls -la
          # hub pr checkout ${{ github.event.issue.number }}
          echo done
