on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = await fetch(context.payload.issue.pull_request.url).then(res => res.json())
            // console.log(JSON.stringify(pr, null, 2))
            console.log(pr.head.ref)

  fastlane:
    if: false

    # if: |
    #   github.event.issue.pull_request &&
    #   startsWith(github.event.comment.body, '/fastlane')

    runs-on: ubuntu-latest

    steps:
      - id: get-pr-branch
        run: echo "BRANCH=$(gh pr view --json headRefName --jq .headRefName $PR_URL)"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.issue.html_url }}

      - uses: circleci-public/trigger-circleci-pipeline-action@v1.2.0
        with:
          target-branch: ${{ steps.get-pr-branch.outputs.BRANCH }}
          GHA_Meta: ${{ github.event.comment.body }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN_SZ }}
