on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  fastlane:
    # if: |
    #   github.event.issue.pull_request &&
    #   startsWith(github.event.comment.body, '/fastlane')

    runs-on: ubuntu-latest

    steps:
      - name: foo
        id: baz
        uses: actions/github-script@v7
        with:
          result-encoding: json
          script: |
            const comment = context.payload.comment.body
            if (!comment.startsWith('/fastlane')) {
              return
            }

            const args = comment.replace('/fastlane', '').trim()

            const pr = await fetch(context.payload.issue.pull_request.url).then(res => res.json())
            const branch = pr.head.ref

            core.setOutput('args', args)
            core.setOutput('branch', branch)

            return {
              args,
              branch,
            }

      - run: |
          echo ${{ steps.baz.outputs.result }}
          echo ${{ steps.baz.outputs.args }}
          echo ${{ steps.baz.outputs.branch }}

      # - uses: circleci-public/trigger-circleci-pipeline-action@v1.2.0
      #   with:
      #     target-branch: ${{ DATA.branch }}
      #     GHA_Meta: ${{ DATA.args }}
      #   env:
      #     DATA: ${{ fromJSON(steps.baz.outputs.result) }}
      #     CCI_TOKEN: ${{ secrets.CCI_TOKEN_SZ }}
