on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  fastlane:
    # if: |
    #   github.event.issue.pull_request &&
    #   startsWith(github.event.comment.body, '/fastlane')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: get-pr-data
        uses: actions/github-script@v7
        with:
          debug: true
          result-encoding: json
          script: require('./.github/test')

      - uses: circleci-public/trigger-circleci-pipeline-action@v1.2.0
        if: steps.get-pr-data.outputs.branch
        with:
          target-branch: ${{ steps.get-pr-data.outputs.branch }}
          GHA_Meta: ${{ steps.get-pr-data.outputs.args }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN_SZ }}
