on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          cmd="/fastlane build platform:android env:staging"
          node -e "'$CMD'.replace('/fastlane', '').trimStart().split(' ').forEach((arg) => console.log(arg))"
