on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: foo
        id: baz
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await fetch(context.payload.issue.pull_request.url).then(res => res.json())
            const branch = pr.head.ref

            const comment = context.payload.comment.body
            const command = comment.startsWith('/fastlane') ? comment.replace('/fastlane', '').trim() : null

            return {
              branch,
              command
            }

      - run: echo "$branch/$command"
        env:
          branch: ${{ steps.baz.outputs.branch }}
          command: ${{ steps.baz.outputs.command }}

  fastlane:
    if: false

    # if: |
    #   github.event.issue.pull_request &&
    #   startsWith(github.event.comment.body, '/fastlane')

    runs-on: ubuntu-latest

    steps:
      - id: get-pr-branch
        run: echo "BRANCH=$(gh pr view --json headRefName --jq .headRefName $PR_URL)"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.issue.html_url }}

      - uses: circleci-public/trigger-circleci-pipeline-action@v1.2.0
        with:
          target-branch: ${{ steps.get-pr-branch.outputs.BRANCH }}
          GHA_Meta: ${{ github.event.comment.body }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN_SZ }}
