on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  fastlane:
    # if: |
    #   github.event.issue.pull_request &&
    #   startsWith(github.event.comment.body, '/fastlane')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: get-pr-data
        uses: actions/github-script@v7
        with:
          result-encoding: json
          script: |
            require('./test.js')
            require('./test')

            const comment = context.payload.comment.body
            if (!comment.startsWith('/fastlane')) {
              return
            }

            const args = comment.replace('/fastlane', '').trim()

            const pr = await fetch(context.payload.issue.pull_request.url).then(res => res.json())
            const branch = pr.head.ref

            core.setOutput('args', args)
            core.setOutput('branch', branch)

      - uses: circleci-public/trigger-circleci-pipeline-action@v1.2.0
        with:
          target-branch: ${{ steps.get-pr-data.outputs.branch }}
          GHA_Meta: ${{ steps.get-pr-data.outputs.args }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN_SZ }}
